title: Axolotl
description: An adorable acquatic creature goes to a technological adventure

remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme

![An smiling axolotl in a tank in the screen](https://alicemcgrath.digital.brynmawr.edu/simple-site/images/janeway.jpg)
